---
name: trigger basic
on: 
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
    - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build project
      run: |
        echo "Build Project in this step"
    - name: Run tests
      run: |
        echo "Run Test in this step"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production server"
